// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laslcfaswstlnshhrosa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhc2xjZmFzd3N0bG5zaGhyb3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NjUwNDgsImV4cCI6MjA3MzA0MTA0OH0.rJvQGgV4ona3UBYMFHu5XK1v00Abv0vLB0BIGEc4eLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});